### PR TITLE
update dm-paperclip for ruby 1.9.2

### PR DESCRIPTION
**Pull request by bunnymatic**
hey there

just made a quick update to the dm-paperclip to support new sprintf in ruby 1.9.2 which seems to fail with nil conversions.

<pre><code>
ruby-1.8.7> sprintf('%d',nil)
=> "0"

ruby-1.9.2> sprintf('%d',nil)
TypeError: can't convert nil into Integer
        from (irb):1:in `sprintf'n = nil
</code></pre>

I looked at all the different forks and it seems like bundler is picking up your original branch.  I tried a couple other forks (gix and solnic) that had more code dev but they had the same issue, so i thought i'd start at the base.  

The fix is simple.  The other mods i've done are just to generalize the tests so they worked on my system (make "require" statements use File.expand_path) and adding a Gemfile so i could build a bundle from which to run the tests.

### CODE REVIEW

**Comment by krobertson** [comment]
Pulling in a number of changes from another fork and they rewrote the make_tmpname method in a way that avoided this issue.  Thanks for the pull req and sorry for the delays.

Have to update the validations for DM 1.2 and then will do a new release.

**Comment by bunnymatic** [comment]
np.  thanks for the info.  i'm looking forward to the new version as it also will have the fix that i just ran into on heroku with NameError uninitialized constant Paperclip::Storage::S3::Merb.

**Comment by krobertson** [comment]
I still haven't gotten to rewriting the validators, but will be soon.

**Comment by bunnymatic** [comment]
That did the trick, by the way.

Again - i appreciate the quick fix.

Cheers
Jon

On Thu, May 17, 2012 at 10:15 AM, Ken Robertson
reply@reply.github.com
wrote:

> I still haven't gotten to rewriting the validators, but will be soon.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/krobertson/dm-paperclip/pull/22#issuecomment-5768866

## 

Visit http://bunnymatic.com

**Comment by conraddecker** [comment]
I'm seeing the "NameError uninitialized constant Paperclip::Storage::S3::Merb" as well. Was this ever fixed? Am I perhaps missing something obvious?

**Pull request closed without merging**
